# Torch Tensors

Intro PyTorch Tensor tutorial: [https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html]([https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html])

In-depth PyTorch Tensor tutorial: [https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)

We talk about and use tensors all the time in machine learning. Tensors are really **multidimensional arrays**

You might think of a tensor like a matrix or the same thing as a tensor from mathematics (multiliner algebra, liek you would find if you have studied general relativity for example); but it's important to keep in mind that matrices and mathemaetical tensors have specific mathematical definitions and properties. Machine learning tensors are really jsut arrays...

## Tensor Basics

In [2]:
import torch
T = torch.tensor([[1,2,3],[4,5,6]]) # Creates a 2x3 tensor from a nested Python list

It's important to understand the shape of a given tensor

In [6]:
T.shape

torch.Size([2, 3])

as well as the numerical type 

In [12]:
T.dtype

torch.int64

We can create tensors of specific `dtype`:

In [15]:
T2 = torch.tensor([[7,8],[9,10]],dtype=torch.float32)

The main selling point of torch tensors is that they are designed to run on GPUs, so let's understand GPU-compatibility right away

In [18]:
# Define device as the device that PyTorch will use
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [22]:
T2.to(device)

tensor([[ 7.,  8.],
        [ 9., 10.]])

Check whether the tensor is stored on the GPU

In [27]:
print(T2.is_cuda)
print(T.device)

False
cpu


We can create tensors filled with specific values e.g. zeros, ones, or random numbers

In [29]:
zero_tensor = torch.zeros(3, 3)
one_tensor = torch.ones(2, 2)
random_tensor = torch.rand(2, 3)


## Tensor Arithmetic

Tensors follow basic arithmetic 

In [51]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

In [43]:
# Operations with a scalar
print(tensor1 + 2)
print(tensor1 - 2)
print(tensor1 * 2)
print(tensor1 / 2)

tensor([3, 4, 5])
tensor([-1,  0,  1])
tensor([2, 4, 6])
tensor([0.5000, 1.0000, 1.5000])


In [53]:
# Addition
print(tensor1 + tensor2)
# Subtraction
print(tensor1 - tensor2)
# Element-wise multiplication
print(tensor1 * tensor2)
# Element-wise division
print(tensor1 / tensor2)
# Element-wise exponentiation 
print(tensor2**tensor1)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([  4,  25, 216])


Note that operations are applied element-wise e.g. multiplication is not like vector or matrix multiplication

**Very important rule**: tensor operations only work if the dimensionality of the tensors is compatible!

In [47]:
tensor3 = torch.tensor([1, 2, 3])
tensor4 = torch.tensor([4, 5, 6, 7])

tensor3+tensor4

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

More advanced mathematical operations are applied element

In [54]:
print(torch.sqrt(tensor1))
print(torch.log(tensor1))
print(torch.cos(tensor1))


tensor([1.0000, 1.4142, 1.7321])
tensor([0.0000, 0.6931, 1.0986])
tensor([ 0.5403, -0.4161, -0.9900])


## Task 1 
Let's consider 100 projecticles fired with random initial velocities and random initial angles
* Create a tensor called `u0` of shape Nx1 with random values between 0 and 10 
* Create a tensor `angle` of same shape with random values between 0 and pi/2. 
* Compute the vertical component of initial velocity of each projectile ($ v_0^y = u_0 \sin(\theta) $)
* Compute the vertical displacement of each projectile after one second ($ y = v_0^yt + \frac{1}{2}gt^2$)

In [60]:
u0 = 10*torch.rand(100)

In [64]:
angle = torch.pi/2*torch.rand(100)

In [66]:
vertical = u0*torch.sin(angle) - 9.8*torch.arange(0,100)

In [71]:
u0*torch.sin(angle) - 9.8*0.5*torch.arange(100)**2

tensor([ 3.0003e-01, -2.8219e+00, -1.3322e+01, -4.0693e+01, -7.1760e+01,
        -1.1480e+02, -1.7350e+02, -2.3451e+02, -3.1325e+02, -3.8921e+02,
        -4.8763e+02, -5.9129e+02, -7.0408e+02, -8.2719e+02, -9.5766e+02,
        -1.0987e+03, -1.2512e+03, -1.4160e+03, -1.5863e+03, -1.7684e+03,
        -1.9528e+03, -2.1571e+03, -2.3641e+03, -2.5872e+03, -2.8220e+03,
        -3.0606e+03, -3.3119e+03, -3.5680e+03, -3.8337e+03, -4.1148e+03,
        -4.4077e+03, -4.7061e+03, -5.0161e+03, -5.3313e+03, -5.6628e+03,
        -6.0020e+03, -6.3492e+03, -6.7074e+03, -7.0687e+03, -7.4500e+03,
        -7.8382e+03, -8.2293e+03, -8.6404e+03, -9.0600e+03, -9.4810e+03,
        -9.9203e+03, -1.0367e+04, -1.0823e+04, -1.1286e+04, -1.1763e+04,
        -1.2245e+04, -1.2744e+04, -1.3248e+04, -1.3760e+04, -1.4288e+04,
        -1.4821e+04, -1.5363e+04, -1.5915e+04, -1.6483e+04, -1.7051e+04,
        -1.7637e+04, -1.8231e+04, -1.8833e+04, -1.9445e+04, -2.0067e+04,
        -2.0702e+04, -2.1344e+04, -2.1991e+04, -2.2

## Combining Tensors

In [117]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

The `stack` operation combines tensors along a new dimension

In [119]:
# Stack vertically (along dim=0)
print(torch.stack((tensor1, tensor2), dim=0))

# Stack horizontally (along dim=1)
print(torch.stack((tensor1, tensor2), dim=1))


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


The `concatenate` operation combines tensors along an existing dimension

In [120]:
print(torch.cat((tensor1, tensor2), dim=0))

tensor([1, 2, 3, 4, 5, 6])


Some reshaping operations for changing the shape of tensors

In [135]:
print(tensor1.reshape(-1,1))
print(tensor1.reshape(-1,1).shape)


tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


## Task 2

Let's make some pretend Large Hadron Collider data

* Create 3 tensors (size 10000x1) corresponding to the $x$, $y$ and $z$ components of 10000 different particles e.g.
```
px = 100*torch.randn(n_events)
```
* Compute a tensor for the energy using the relation $E^2 = p_x^2 + p_y^2 + p_z^2 + m^2$ where we will assume the energy to be zero.
* Combine the four tensors into one tensor of shape (10000,4)
* Filter the array: return a sub-array containing only particles (rows) which have $\sqrt{p_x^2 + p_y^2} > 50$
* Find the largest $p_z$ value in the array
* Find the index of particles with the largest and the smallest energy
* Normlise each column of such that the values lie between -1 and 1 

In [106]:
import torch

# Number of events
n_events = 10000

# Rest mass of the particle (assumed to be 1.0 for this example)
m = 0.0

# Randomly generate 3-momentum components (px, py, pz)
px = 100*torch.randn(n_events)  # Random px values from normal distribution
py = 100*torch.randn(n_events)  # Random py values from normal distribution
pz = 100*torch.randn(n_events)  # Random pz values from normal distribution

# Calculate the energy E using the relativistic energy-momentum relation
E = torch.sqrt(px**2 + py**2 + pz**2 + m**2)

# Stack the 4-momentum components into a tensor of shape (n_events, 4)
momentum_tensor = torch.stack((px, py, pz, E), dim=1)

# Print out the shape of the resulting tensor
print(momentum_tensor.shape)  # Should be (10000, 4)
print(momentum_tensor)  # Print first few events for inspection

# Apply a mask to filter out events with momentum magnitude greater than 50
mask = torch.sqrt((momentum_tensor[:,0]**2) + (momentum_tensor[:,1]**2))>50
filtered_momentum_tensor = momentum_tensor[mask]

# Print the results
print(filtered_momentum_tensor.shape)
print(filtered_momentum_tensor)

# Use torch.max to find the maximum value of the z-component of the momentum
print(torch.max(filtered_momentum_tensor[:,2]))

# Use torch.arg and torch.argmin to find the index of the maximum and minimum values of the energy
print(torch.argmax(filtered_momentum_tensor[:,3]))
print(torch.argmin(filtered_momentum_tensor[:,3]))

# Normalise each column's values to lie between -1 and 1
normalised_momentum_tensor = 2*(filtered_momentum_tensor - torch.min(filtered_momentum_tensor, dim=0).values) / (torch.max(filtered_momentum_tensor, dim=0).values - torch.min(filtered_momentum_tensor, dim=0).values) - 1
print(normalised_momentum_tensor)


torch.Size([10000, 4])
tensor([[ 15.2211, -57.6250, 120.9803, 134.8650],
        [170.4215,  82.7710, -45.4076, 194.8239],
        [ 85.0652,  66.0822, -47.6920, 117.8027],
        ...,
        [-48.1688, -89.3967, -11.0948, 102.1523],
        [102.6607,  38.2144,  79.1791, 135.1625],
        [-29.6655, 189.6720, 117.3229, 224.9893]])
torch.Size([8827, 4])
tensor([[ 15.2211, -57.6250, 120.9803, 134.8650],
        [170.4215,  82.7710, -45.4076, 194.8239],
        [ 85.0652,  66.0822, -47.6920, 117.8027],
        ...,
        [-48.1688, -89.3967, -11.0948, 102.1523],
        [102.6607,  38.2144,  79.1791, 135.1625],
        [-29.6655, 189.6720, 117.3229, 224.9893]])
tensor(421.6800)
tensor(8281)
tensor(3821)
tensor([[ 0.1101, -0.0282,  0.2214, -0.6067],
        [ 0.5158,  0.3045, -0.2094, -0.3288],
        [ 0.2926,  0.2650, -0.2153, -0.6858],
        ...,
        [-0.0556, -0.1035, -0.1205, -0.7584],
        [ 0.3386,  0.1989,  0.1132, -0.6054],
        [-0.0073,  0.5579,  0.2120, -0.18